name: Build LaTeX document
on:
  push:
    tags:
      - 'v*.*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
        # TODO: Adjust filename
          root_file: filename.tex

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          # TODO: Adjust filename
          artifacts: "filename.pdf, LICENSE"
